<?php

use Illuminate\Database\Seeder;

class TimezoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('hris_time_zones')->delete();

        $timezone = array(

	       	array('utc' => '(UTC-11:00)', 'name' => 'Pacific/Midway'),
		    array('utc' => '(UTC-11:00)', 'name' => 'Pacific/Samoa'),
		    array('utc' => '(UTC-10:00)', 'name' => 'Pacific/Honolulu'),
		    array('utc' => '(UTC-09:00)', 'name' => 'US/Alaska'),
		    array('utc' => '(UTC-08:00)', 'name' => 'America/Los_Angeles'),
		    array('utc' => '(UTC-08:00)', 'name' => 'America/Tijuana'),
		    array('utc' => '(UTC-07:00)', 'name' => 'US/Arizona'),
		    array('utc' => '(UTC-07:00)', 'name' => 'America/Chihuahua'),
		    array('utc' => '(UTC-07:00)', 'name' => 'America/Chihuahua'),
		    array('utc' => '(UTC-07:00)', 'name' => 'America/Mazatlan'),
		    array('utc' => '(UTC-07:00)', 'name' => 'US/Mountain'),
		    array('utc' => '(UTC-06:00)', 'name' => 'America/Managua'),
		    array('utc' => '(UTC-06:00)', 'name' => 'US/Central'),
		    array('utc' => '(UTC-06:00)', 'name' => 'America/Mexico_City'),
		    array('utc' => '(UTC-06:00)', 'name' => 'America/Mexico_City'),
		    array('utc' => '(UTC-06:00)', 'name' => 'America/Monterrey'),
		    array('utc' => '(UTC-06:00)', 'name' => 'Canada/Saskatchewan'),
		    array('utc' => '(UTC-05:00)', 'name' => 'America/Bogota'),
		    array('utc' => '(UTC-05:00)', 'name' => 'US/Eastern'),
		    array('utc' => '(UTC-05:00)', 'name' => 'US/East-Indiana'),
		    array('utc' => '(UTC-05:00)', 'name' => 'America/Lima'),
		    array('utc' => '(UTC-05:00)', 'name' => 'America/Bogota'),
		    array('utc' => '(UTC-04:00)', 'name' => 'Canada/Atlantic'),
		    array('utc' => '(UTC-04:30)', 'name' => 'America/Caracas'),
		    array('utc' => '(UTC-04:00)', 'name' => 'America/La_Paz'),
		    array('utc' => '(UTC-04:00)', 'name' => 'America/Santiago'),
		    array('utc' => '(UTC-03:30)', 'name' => 'Canada/Newfoundland'),
		    array('utc' => '(UTC-03:00)', 'name' => 'America/Sao_Paulo'),
		    array('utc' => '(UTC-03:00)', 'name' => 'America/Argentina/Buenos_Aires'),
		    array('utc' => '(UTC-03:00)', 'name' => 'America/Argentina/Buenos_Aires'),
		    array('utc' => '(UTC-03:00)', 'name' => 'America/Godthab'),
		    array('utc' => '(UTC-02:00)', 'name' => 'America/Noronha'),
		    array('utc' => '(UTC-01:00)', 'name' => 'Atlantic/Azores'),
		    array('utc' => '(UTC-01:00)', 'name' => 'Atlantic/Cape_Verde'),
		    array('utc' => '(UTC+00:00)', 'name' => 'Africa/Casablanca'),
		    array('utc' => '(UTC+00:00)', 'name' => 'Europe/London'),
		    array('utc' => '(UTC+00:00)', 'name' => 'Etc/Greenwich'),
		    array('utc' => '(UTC+00:00)', 'name' => 'Europe/Lisbon'),
		    array('utc' => '(UTC+00:00)', 'name' => 'Europe/London'),
		    array('utc' => '(UTC+00:00)', 'name' => 'Africa/Monrovia'),
		    array('utc' => '(UTC+00:00)', 'name' => 'UTC'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Amsterdam'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Belgrade'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Berlin'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Berlin'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Bratislava'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Brussels'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Budapest'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Copenhagen'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Ljubljana'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Madrid'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Paris'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Prague'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Rome'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Sarajevo'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Skopje'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Stockholm'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Vienna'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Warsaw'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Africa/Lagos'),
		    array('utc' => '(UTC+01:00)', 'name' => 'Europe/Zagreb'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Athens'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Bucharest'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Africa/Cairo'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Africa/Harare'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Helsinki'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Istanbul'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Asia/Jerusalem'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Helsinki'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Africa/Johannesburg'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Riga'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Sofia'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Tallinn'),
		    array('utc' => '(UTC+02:00)', 'name' => 'Europe/Vilnius'),
		    array('utc' => '(UTC+03:00)', 'name' => 'Asia/Baghdad'),
		    array('utc' => '(UTC+03:00)', 'name' => 'Asia/Kuwait'),
		    array('utc' => '(UTC+03:00)', 'name' => 'Europe/Minsk'),
		    array('utc' => '(UTC+03:00)', 'name' => 'Europe/Moscow'),
		    array('utc' => '(UTC+03:00)', 'name' => 'Africa/Nairobi'),
		    array('utc' => '(UTC+03:00)', 'name' => 'Asia/Riyadh'),
		    array('utc' => '(UTC+03:00)', 'name' => 'Europe/Moscow'),
		    array('utc' => '(UTC+03:00)', 'name' => 'Europe/Volgograd'),
		    array('utc' => '(UTC+03:30)', 'name' => 'Asia/Tehran'),
		    array('utc' => '(UTC+04:00)', 'name' => 'Asia/Muscat'),
		    array('utc' => '(UTC+04:00)', 'name' => 'Asia/Baku'),	    
		    array('utc' => '(UTC+04:00)', 'name' => 'Asia/Muscat'),	    
		    array('utc' => '(UTC+04:00)', 'name' => 'Asia/Tbilisi'),
		    array('utc' => '(UTC+04:00)', 'name' => 'Asia/Yerevan'),
		    array('utc' => '(UTC+04:30)', 'name' => 'Asia/Kabul'),
		    array('utc' => '(UTC+05:00)', 'name' => 'Asia/Yekaterinburg'),
		    array('utc' => '(UTC+05:00)', 'name' => 'Asia/Karachi'),
		    array('utc' => '(UTC+05:00)', 'name' => 'Asia/Karachi'),
		    array('utc' => '(UTC+05:00)', 'name' => 'Asia/Tashkent'),
		    array('utc' => '(UTC+05:30)', 'name' => 'Asia/Calcutta'),
		    array('utc' => '(UTC+05:30)', 'name' => 'Asia/Kolkata'),
		    array('utc' => '(UTC+05:30)', 'name' => 'Asia/Calcutta'),
		    array('utc' => '(UTC+05:30)', 'name' => 'Asia/Calcutta'),
		    array('utc' => '(UTC+05:30)', 'name' => 'Asia/Calcutta'),
		    array('utc' => '(UTC+05:45)', 'name' => 'Asia/Katmandu'),
		    array('utc' => '(UTC+06:00)', 'name' => 'Asia/Almaty'),
		    array('utc' => '(UTC+06:00)', 'name' => 'Asia/Dhaka'),
		    array('utc' => '(UTC+06:00)', 'name' => 'Asia/Dhaka'),	    
		    array('utc' => '(UTC+06:00)', 'name' => 'Asia/Novosibirsk'),
		    array('utc' => '(UTC+06:30)', 'name' => 'Asia/Rangoon'),
		    array('utc' => '(UTC+07:00)', 'name' => 'Asia/Bangkok'),
		    array('utc' => '(UTC+07:00)', 'name' => 'Asia/Bangkok'),
		    array('utc' => '(UTC+07:00)', 'name' => 'Asia/Jakarta'),
		    array('utc' => '(UTC+07:00)', 'name' => 'Asia/Krasnoyarsk'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Hong_Kong'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Chongqing'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Hong_Kong'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Irkutsk'),	    
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Kuala_Lumpur'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Manila'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Australia/Perth'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Singapore'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Taipei'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Ulan_Bator'),
		    array('utc' => '(UTC+08:00)', 'name' => 'Asia/Urumqi'),	    
		    array('utc' => '(UTC+09:00)', 'name' => 'Asia/Tokyo'),
		    array('utc' => '(UTC+09:00)', 'name' => 'Asia/Tokyo'),
		    array('utc' => '(UTC+09:00)', 'name' => 'Asia/Seoul'),
		    array('utc' => '(UTC+09:00)', 'name' => 'Asia/Tokyo'),
		    array('utc' => '(UTC+09:00)', 'name' => 'Asia/Yakutsk'),
		    array('utc' => '(UTC+09:30)', 'name' => 'Australia/Adelaide'),
		    array('utc' => '(UTC+09:30)', 'name' => 'Australia/Darwin'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Australia/Brisbane'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Australia/Canberra'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Pacific/Guam'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Australia/Hobart'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Asia/Magadan'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Australia/Melbourne'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Pacific/Port_Moresby'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Australia/Sydney'),
		    array('utc' => '(UTC+10:00)', 'name' => 'Asia/Vladivostok'),
		    array('utc' => '(UTC+12:00)', 'name' => 'Pacific/Auckland'),
		    array('utc' => '(UTC+12:00)', 'name' => 'Pacific/Fiji'),
		    array('utc' => '(UTC+12:00)', 'name' => 'Pacific/Kwajalein'),
		    array('utc' => '(UTC+12:00)', 'name' => 'Asia/Kamchatka'),	    
		    array('utc' => '(UTC+12:00).', 'name' => 'Pacific/Fiji'),
		    array('utc' => '(UTC+12:00)', 'name' => 'Asia/Magadan'),
		    array('utc' => '(UTC+12:00).', 'name' => 'Asia/Magadan'),
		    array('utc' => '(UTC+12:00)', 'name' => 'Pacific/Auckland'),
		    array('utc' => '(UTC+13:00)', 'name' => 'Pacific/Tongatapu')

        );

		DB::table('hris_time_zones')->insert($timezone);
    }
}
